src/Entity/Player.php
<?php

namespace App\Entity;

use App\Repository\PlayerRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayerRepository::class)]
class Player
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Surname = null;

    #[ORM\Column]
    private ?int $Age = null;

    #[ORM\ManyToOne(inversedBy: 'players')]
    private ?Team $Team = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->Surname;
    }

    public function setSurname(string $Surname): static
    {
        $this->Surname = $Surname;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): static
    {
        $this->Age = $Age;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->Team;
    }

    public function setTeam(?Team $Team): static
    {
        $this->Team = $Team;

        return $this;
    }
}

src/Form/PlayerType.php
<?php

namespace App\Form;

use App\Entity\Player;
use App\Entity\Team;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlayerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name')
            ->add('Surname')
            ->add('Age')
            ->add('Team', EntityType::class, [
                'class' => Team::class,
                'choice_label' => 'name',
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Player::class,
        ]);
    }
}

src/Controller/PlayerController.php
<?php

namespace App\Controller;

use App\Entity\Player;
use App\Form\PlayerType;
use App\Repository\PlayerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/player')]
class PlayerController extends AbstractController
{
    #[Route('/', name: 'app_player_index', methods: ['GET'])]
    public function index(PlayerRepository $playerRepository): Response
    {
        return $this->render('player/index.html.twig', [
            'players' => $playerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_player_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $player = new Player();
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($player);
            $entityManager->flush();

            return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('player/new.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_player_show', methods: ['GET'])]
    public function show(Player $player): Response
    {
        return $this->render('player/show.html.twig', [
            'player' => $player,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_player_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Player $player, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlayerType::class, $player);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('player/edit.html.twig', [
            'player' => $player,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_player_delete', methods: ['POST'])]
    public function delete(Request $request, Player $player, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, "You don't have admin role to perform deletion.");
        $entityManager->remove($player);
        $entityManager->flush();

        return $this->redirectToRoute('app_player_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/player/_delete_form.html.twig
<form method="post" action="{{ path('app_player_delete', {'id': player.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ player.id) }}">
    <button class="btn btn-danger mt-2">Delete</button>
</form>

templates/player/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/player/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Player{% endblock %}

{% block body %}
    <h1>Edit Player</h1>

    {{ include('player/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-secondary mt-2" href="{{ path('app_player_index') }}">back to list</a>

    {{ include('player/_delete_form.html.twig') }}
{% endblock %}

templates/player/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Players{% endblock %}

{% block body %}
    <h1>Players</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Age</th>
            <th>Team</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td>{{ player.id }}</td>
                <td>{{ player.Name }}</td>
                <td>{{ player.Surname }}</td>
                <td>{{ player.Age }}</td>
                <td>{{ player.team ? player.team.name : '' }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('app_player_show', {'id': player.id}) }}">show</a>
                    <a class="btn btn-secondary" href="{{ path('app_player_edit', {'id': player.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_player_new') }}">Create new</a>
{% endblock %}

templates/player/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Player{% endblock %}

{% block body %}
    <h1>Create new Player</h1>

    {{ include('player/_form.html.twig') }}

    <a class="btn btn-secondary mt-2" href="{{ path('app_player_index') }}">back to list</a>
{% endblock %}

templates/player/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Player{% endblock %}

{% block body %}
    <h1>Player</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ player.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ player.Name }}</td>
        </tr>
        <tr>
            <th>Surname</th>
            <td>{{ player.Surname }}</td>
        </tr>
        <tr>
            <th>Age</th>
            <td>{{ player.Age }}</td>
        </tr>
        <tr>
            <th>Team</th>
            <td>{{ player.team ? player.team.name : '' }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('app_player_index') }}">back to list</a>

    <a href="{{ path('app_player_edit', {'id': player.id}) }}">edit</a>

    {{ include('player/_delete_form.html.twig') }}
{% endblock %}