src/Entity/Player.php
<?php

namespace App\Entity;

use App\Repository\PlayerRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayerRepository::class)]
class Player
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 255)]
    private ?string $Surname = null;

    #[ORM\Column]
    private ?int $Age = null;

    #[ORM\ManyToOne(inversedBy: 'players')]
    private ?Team $Team = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->Surname;
    }

    public function setSurname(string $Surname): static
    {
        $this->Surname = $Surname;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): static
    {
        $this->Age = $Age;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->Team;
    }

    public function setTeam(?Team $Team): static
    {
        $this->Team = $Team;

        return $this;
    }
}

src/Entity/Team.php
<?php

namespace App\Entity;

use App\Repository\TeamRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TeamRepository::class)]
class Team
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\ManyToMany(targetEntity: Championship::class, inversedBy: 'teams')]
    private Collection $Championship;

    #[ORM\OneToMany(mappedBy: 'Team', targetEntity: Player::class)]
    private Collection $players;

    public function __construct()
    {
        $this->Championship = new ArrayCollection();
        $this->players = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    /**
     * @return Collection<int, Championship>
     */
    public function getChampionship(): Collection
    {
        return $this->Championship;
    }

    public function addChampionship(Championship $championship): static
    {
        if (!$this->Championship->contains($championship)) {
            $this->Championship->add($championship);
        }

        return $this;
    }

    public function removeChampionship(Championship $championship): static
    {
        $this->Championship->removeElement($championship);

        return $this;
    }

    /**
     * @return Collection<int, Player>
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Player $player): static
    {
        if (!$this->players->contains($player)) {
            $this->players->add($player);
            $player->setTeam($this);
        }

        return $this;
    }

    public function removePlayer(Player $player): static
    {
        if ($this->players->removeElement($player)) {
            // set the owning side to null (unless already changed)
            if ($player->getTeam() === $this) {
                $player->setTeam(null);
            }
        }

        return $this;
    }
}

src/Form/TeamType.php
<?php

namespace App\Form;

use App\Entity\Championship;
use App\Entity\Player;
use App\Entity\Team;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TeamType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Name')
            ->add('Championship', EntityType::class, [
                'class' => Championship::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Team::class,
        ]);
    }
}

src/Controller/TeamController.php
<?php

namespace App\Controller;

use App\Entity\Team;
use App\Form\TeamType;
use App\Repository\TeamRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/team')]
class TeamController extends AbstractController
{
    #[Route('/', name: 'app_team_index', methods: ['GET'])]
    public function index(TeamRepository $teamRepository): Response
    {
        return $this->render('team/index.html.twig', [
            'teams' => $teamRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_team_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $team = new Team();
        $form = $this->createForm(TeamType::class, $team);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($team);
            $entityManager->flush();

            return $this->redirectToRoute('app_team_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('team/new.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_team_show', methods: ['GET'])]
    public function show(Team $team): Response
    {
        return $this->render('team/show.html.twig', [
            'team' => $team,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_team_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Team $team, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TeamType::class, $team);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_team_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('team/edit.html.twig', [
            'team' => $team,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_team_delete', methods: ['POST'])]
    public function delete(Request $request, Team $team, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, "You don't have admin role to perform deletion.");
        // Remove or update associated players before removing the team
        foreach ($team->getPlayers() as $player) {
            $player->setTeam(null);
            $entityManager->persist($player);
        }

        $entityManager->remove($team);
        $entityManager->flush();

        return $this->redirectToRoute('app_team_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/team/_delete_form.html.twig
<form method="post" action="{{ path('app_team_delete', {'id': team.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ team.id) }}">
    <button class="btn btn-danger mt-2">Delete</button>
</form>

templates/team/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/team/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Team{% endblock %}

{% block body %}
    <h1>Edit Team</h1>

    {{ include('team/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-secondary mt-2" href="{{ path('app_team_index') }}">back to list</a>

    {{ include('team/_delete_form.html.twig') }}
{% endblock %}

templates/team/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Teams{% endblock %}

{% block body %}
    <h1>Teams</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Championships</th>
            <th>Players</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for team in teams %}
            <tr>
                <td>{{ team.id }}</td>
                <td>{{ team.Name }}</td>
                <td>
                    <ul>
                        {% for championship in team.championship %}
                            <li>
                                {{ championship.name }}
                            </li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul>
                        {% for player in team.players %}
                            <li>
                                {{ player.name ~ ' ' ~ player.surname }}
                            </li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <a class="btn btn-primary" href="{{ path('app_team_show', {'id': team.id}) }}">show</a>
                    <a class="btn btn-secondary" href="{{ path('app_team_edit', {'id': team.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('app_team_new') }}">Create new</a>
{% endblock %}

templates/team/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Team{% endblock %}

{% block body %}
    <h1>Create new Team</h1>

    {{ include('team/_form.html.twig') }}

    <a class="btn btn-secondary mt-2" href="{{ path('app_team_index') }}">back to list</a>
{% endblock %}

templates/team/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Team{% endblock %}

{% block body %}
    <h1>Team</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ team.id }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ team.Name }}</td>
        </tr>
        <tr>
            <th>Championships</th>
            <td>
                <ul>
                    {% for championship in team.championship %}
                        <li>
                            {{ championship.name }}
                        </li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        <tr>
            <th>Players</th>
            <td>
                <ul>
                    {% for player in team.players %}
                        <li>
                            {{ player.name ~ ' ' ~ player.surname }}
                        </li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        </tbody>
    </table>

    <a class="btn btn-secondary" href="{{ path('app_team_index') }}">back to list</a>

    <a class="btn btn-primary" href="{{ path('app_team_edit', {'id': team.id}) }}">edit</a>

    {{ include('team/_delete_form.html.twig') }}
{% endblock %}